#!/bin/bash
SRC="/Volumes/MySSD/work/dev/lucky_nest_monorepo/apps/mini-shop-admin/src"
DEST="/Volumes/MySSD/work/dev/lucky_nest_monorepo/apps/admin-next/src"

cp "$SRC/store/useAppStore.ts" "$DEST/store/useAppStore.ts"
cp "$SRC/store/useToastStore.ts" "$DEST/store/useToastStore.ts"
cp "$SRC/type/types.ts" "$DEST/type/types.ts"
cp "$SRC/type/search.ts" "$DEST/type/search.ts" 2>/dev/null || true
cp "$SRC/api/types.ts" "$DEST/api/types.ts"
cp "$SRC/api/http.ts" "$DEST/api/http.ts"
cp "$SRC/api/index.ts" "$DEST/api/index.ts"
cp -r "$SRC/components/scaffold/." "$DEST/components/scaffold/"
cp -r "$SRC/components/ui/." "$DEST/components/ui/"
cp "$SRC/components/UIComponents.tsx" "$DEST/components/UIComponents.tsx"
cp "$SRC/pages/Dashboard.tsx" "$DEST/pages/Dashboard.tsx"
cp "$SRC/pages/UserManagement.tsx" "$DEST/pages/UserManagement.tsx"
cp "$SRC/pages/AdminUserManagement.tsx" "$DEST/pages/AdminUserManagement.tsx"
cp "$SRC/pages/BannerManagement.tsx" "$DEST/pages/BannerManagement.tsx"
cp "$SRC/pages/CategoryManagement.tsx" "$DEST/pages/CategoryManagement.tsx"
cp "$SRC/pages/ActSectionManagement.tsx" "$DEST/pages/ActSectionManagement.tsx"
cp "$SRC/pages/GroupManagement.tsx" "$DEST/pages/GroupManagement.tsx"
cp "$SRC/pages/OrderManagement.tsx" "$DEST/pages/OrderManagement.tsx"
cp "$SRC/pages/KycList.tsx" "$DEST/pages/KycList.tsx"
cp "$SRC/pages/AddressList.tsx" "$DEST/pages/AddressList.tsx"
cp "$SRC/pages/Finance.tsx" "$DEST/pages/Finance.tsx"
cp "$SRC/pages/FinancePage.tsx" "$DEST/pages/FinancePage.tsx"
cp "$SRC/pages/PaymentChannelList.tsx" "$DEST/pages/PaymentChannelList.tsx"
cp "$SRC/pages/ProductManagement.tsx" "$DEST/pages/ProductManagement.tsx"
cp "$SRC/pages/Marketing.tsx" "$DEST/pages/Marketing.tsx"
cp "$SRC/pages/Marketing/Coupon.tsx" "$DEST/pages/Marketing/Coupon.tsx"
cp "$SRC/pages/Marketing/CouponModal.tsx" "$DEST/pages/Marketing/CouponModal.tsx"
cp "$SRC/pages/user-management/UserDetailModal.tsx" "$DEST/pages/user-management/UserDetailModal.tsx"
cp -r "$SRC/pages/product/." "$DEST/pages/product/"
cp -r "$SRC/pages/kyc/." "$DEST/pages/kyc/"
cp -r "$SRC/pages/finance/." "$DEST/pages/finance/"
cp -r "$SRC/pages/act-section/." "$DEST/pages/act-section/"
cp -r "$SRC/pages/banner/." "$DEST/pages/banner/"
cp -r "$SRC/pages/admin/." "$DEST/pages/admin/"
cp -r "$SRC/pages/payment-channel/." "$DEST/pages/payment-channel/"
cp -r "$SRC/pages/category/." "$DEST/pages/category/"
cp -r "$SRC/pages/address/." "$DEST/pages/address/"
echo "Done!"

