services:
  # base image, for api, admin service , they all use it for build
  monorepo-base:
    build:
      context: .
      dockerfile: Dockerfile.base
      tags:
        - lucky-monorepo-base:latest
    # it's a dummy command, just to make sure the image is built
    command: [ "true" ]
  # backend service, it's a monorepo service'
  backend:
    #use dockerfile to build our image
    build:
      context: .
      dockerfile: apps/api/Dockerfile.dev
    # update the command to start the dev server with hot-reloading
    command: >
      sh -lc "corepack enable &&
              yarn install --immutable &&
              yarn workspace @lucky/api start:dev"
    # after build, use image
    image: lucky-backend-dev:latest
    # container name
    container_name: lucky-backend-dev
    # environment variables,db url, etc.
    env_file:
      - apps/api/.env.docker
    expose:
      - "3000"
    volumes:
      # 挂载整个仓库，内部包源码可用
      - .:/app
      # 避免宿主机空目录覆盖容器依赖
      #- /app/node_modules
      #- /app/apps/api/node_modules
    environment:
      # macOS/WSL 下文件监听更稳
      CHOKIDAR_USEPOLLING: "true"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks: [ app ]

  # Nginx service, to serve as reverse proxy for backend and admin
  nginx:
    image: nginx:latest
    container_name: lucky-nginx-dev
    extra_hosts:
      - "host.docker.internal:host-gateway" # for docker networking on linux
    ports:
      - "80:80"
      - "443:443" # for https later
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/whitelist.conf:/etc/nginx/conf.d/whitelist.conf
      - ./certs:/etc/nginx/certs # for https later
      - ./nginx/html:/var/www/html
    depends_on:
      - backend
      - mini-shop-admin
    networks: [ app ]

  # mini-shop-admin
  mini-shop-admin:
    build:
      context: .
      dockerfile: apps/mini-shop-admin/Dockerfile.dev
    container_name: lucky-mini-shop-admin-dev
    expose:
      - "4000"
    volumes:
      - .:/app
    depends_on:
      - backend
    networks: [ app ]

  # redis service, for caching and session storage
  redis:
    image: redis:7
    container_name: lucky-redis
    command: redis-server /etc/redis/redis.conf --requirepass "${REDIS_PASSWORD}"
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - /Volumes/MySSD/docker-data/redis:/data # write to SSD
      - ./redis/redis.conf:/etc/redis/redis.conf
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli -a $$REDIS_PASSWORD ping | grep PONG" ]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - app
  # postgres service, for database
  db:
    image: postgres:16
    container_name: lucky-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - /Volumes/MySSD/docker-data/postgres:/var/lib/postgresql/data # write to SSD
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -h 127.0.0.1 -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - app

networks:
  app:


volumes:
  db_data:
  redis_data: