# 1. 全局 Gzip
gzip on;
gzip_min_length 1k;
gzip_types application/json text/plain application/javascript text/css application/xml;

# ==========================================
# HTTPS Server (443)
# ==========================================
server {
    listen 443 ssl http2;
    server_name admin.joyminis.com dev-api.joyminis.com dev.joyminis.com;

    ssl_certificate     /etc/nginx/certs/admin.joyminis.com+4.pem;
    ssl_certificate_key /etc/nginx/certs/admin.joyminis.com+4-key.pem;

    #  救火关键 1：不要拦截 cdn-cgi，把它当做普通请求转发给 R2
    # 虽然 R2 不支持裁剪，但至少能返回原图，不报 404
    location ~* ^/(cdn-cgi|uploads)/.*\.(jpg|jpeg|png|webp|gif|avif|mp4|mov|m4a)$ {
       # 【核心修正：关闭缓冲】
       # 告诉 Nginx 收到数据就立马发给 App，别存硬盘！解决“卡好久”的问题。
       proxy_buffering off;

        proxy_http_version 1.1;
        proxy_set_header Range $http_range;
        proxy_pass_header Content-Range;
        proxy_pass_header Accept-Ranges;

        # 伪装 UA，尝试触发 Cloudflare 隐式优化
        proxy_set_header User-Agent "Mozilla/5.0 (iPhone; CPU iPhone OS 16_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.6 Mobile/15E148 Safari/604.1";

        proxy_pass https://img.joyminis.com;
        proxy_set_header Host img.joyminis.com;
        proxy_ssl_server_name on;
        proxy_ssl_verify off;
    }

    # 🚀 救火关键 2：API 简单粗暴允许所有跨域 (先跑通再说)
    location /api/ {
        if ($request_method = 'OPTIONS') {
            add_header Access-Control-Allow-Origin '*' always;
            add_header Access-Control-Allow-Methods 'GET, POST, OPTIONS, PUT, DELETE, PATCH' always;
            add_header Access-Control-Allow-Headers '*' always;
            add_header Access-Control-Max-Age 1728000 always;
            add_header Content-Type 'text/plain; charset=utf-8';
            add_header Content-Length 0;
            return 204;
        }

        add_header Access-Control-Allow-Origin '*' always;
        add_header Access-Control-Allow-Headers '*' always;

        proxy_pass http://backend:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # WebSocket
    location ^~ /socket.io/ {
        proxy_pass http://backend:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
    }

    # Admin 前端
    location / {
        proxy_pass http://mini-shop-admin:4000;
    }
}

# HTTP 80 端口转发
server {
    listen 80;
    server_name dev.joyminis.com;
    location / {
        return 301 https://$host$request_uri;
    }
}