#!/usr/bin/env bash
# ============================================================
# Install / Recover TURN server (coturn) on Ubuntu VPS
# ============================================================
# Usage:
#   export TURN_SECRET='replace-with-a-long-random-secret'
#   export TURN_PUBLIC_IP='YOUR_VPS_PUBLIC_IP'   # optional: auto-detect if omitted
#   export TURN_DOMAIN='turn.joyminis.com'       # optional: defaults to TURN_PUBLIC_IP
#   bash deploy/install-turn.sh
#
# After install, set in /opt/lucky/deploy/.env.prod:
#   TURN_SECRET=<same secret as below>
#   TURN_URL=turn:<TURN_DOMAIN_OR_IP>:3478?transport=udp
# ============================================================
set -euo pipefail

TURN_SECRET="${TURN_SECRET:-}"
TURN_PUBLIC_IP="${TURN_PUBLIC_IP:-}"
TURN_DOMAIN="${TURN_DOMAIN:-}"
TURN_PORT="${TURN_PORT:-3478}"
TURN_MIN_PORT="${TURN_MIN_PORT:-49160}"
TURN_MAX_PORT="${TURN_MAX_PORT:-49200}"
TURN_CONF="/etc/turnserver.conf"
TURN_DEFAULTS="/etc/default/coturn"

log() { echo "[TURN] $*"; }
err() { echo "[TURN][ERROR] $*"; exit 1; }

if [ -z "$TURN_SECRET" ]; then
  err "TURN_SECRET is required. Example: export TURN_SECRET='replace-with-a-long-random-secret'"
fi

if [ -z "$TURN_PUBLIC_IP" ]; then
  TURN_PUBLIC_IP="$(curl -4 -fsSL https://api.ipify.org || true)"
fi

if [ -z "$TURN_PUBLIC_IP" ]; then
  err "Could not auto-detect TURN_PUBLIC_IP. Please export TURN_PUBLIC_IP and rerun."
fi

if [ -z "$TURN_DOMAIN" ]; then
  TURN_DOMAIN="$TURN_PUBLIC_IP"
fi

log "Installing coturn..."
apt-get update -y
apt-get install -y coturn ufw

log "Enabling coturn service..."
if grep -q '^#TURNSERVER_ENABLED=1' "$TURN_DEFAULTS" 2>/dev/null; then
  sed -i 's/^#TURNSERVER_ENABLED=1/TURNSERVER_ENABLED=1/' "$TURN_DEFAULTS"
elif grep -q '^TURNSERVER_ENABLED=' "$TURN_DEFAULTS" 2>/dev/null; then
  sed -i 's/^TURNSERVER_ENABLED=.*/TURNSERVER_ENABLED=1/' "$TURN_DEFAULTS"
else
  echo 'TURNSERVER_ENABLED=1' >> "$TURN_DEFAULTS"
fi

if [ -f "$TURN_CONF" ]; then
  cp "$TURN_CONF" "${TURN_CONF}.bak.$(date +%Y%m%d_%H%M%S)"
fi

log "Writing $TURN_CONF ..."
cat > "$TURN_CONF" <<EOF
# Lucky Nest coturn configuration
# Generated by deploy/install-turn.sh

listening-port=${TURN_PORT}
listening-ip=${TURN_PUBLIC_IP}
external-ip=${TURN_PUBLIC_IP}

min-port=${TURN_MIN_PORT}
max-port=${TURN_MAX_PORT}

use-auth-secret
static-auth-secret=${TURN_SECRET}
realm=${TURN_DOMAIN}
lt-cred-mech

fingerprint
no-cli
no-multicast-peers

# Keep first install simple: UDP/TCP on 3478 only.
# If you later need TLS, add certs and enable 5349 separately.
no-tls
no-dtls

simple-log
log-file=/var/log/turnserver.log
EOF

log "Opening firewall ports..."
ufw allow ${TURN_PORT}/tcp || true
ufw allow ${TURN_PORT}/udp || true
ufw allow ${TURN_MIN_PORT}:${TURN_MAX_PORT}/udp || true
ufw reload || true

log "Starting coturn..."
systemctl enable coturn
systemctl restart coturn
sleep 2
systemctl --no-pager --full status coturn || true

cat <<EOF

============================================================
TURN install complete.
============================================================
TURN_PUBLIC_IP : ${TURN_PUBLIC_IP}
TURN_DOMAIN    : ${TURN_DOMAIN}
TURN_PORT      : ${TURN_PORT}
RELAY PORTS    : ${TURN_MIN_PORT}-${TURN_MAX_PORT}/udp

Next steps:
1. Put these values into /opt/lucky/deploy/.env.prod

   TURN_SECRET=${TURN_SECRET}
   TURN_URL=turn:${TURN_DOMAIN}:3478?transport=udp

2. Restart backend:

   cd /opt/lucky
   docker compose -f compose.prod.yml --env-file deploy/.env.prod up -d --no-build --force-recreate backend

3. Verify turnserver is listening:

   ss -lntup | grep ${TURN_PORT}
   tail -n 100 /var/log/turnserver.log

============================================================
EOF

