# Use the base image from the repository Dockerfile
# This Dockerfile is for the development environment of the Admin workspace.
# It uses the base image defined in Dockerfile.base as its starting point.
# before_script: docker build -f Dockerfile.base -t lucky-monorepo-base .
# you should run this command to build the base image before building this Dockerfile.

FROM lucky-monorepo-base

WORKDIR /app

COPY . .

EXPOSE 3000

CMD ["yarn", "workspace", "@lucky/admin", "dev", "-H", "0.0.0.0"]