// *** AUTO-GENERATED. DO NOT EDIT. ***
// Source: Google Sheets (1E1otNTsU-GVKPvEf7qaC3dsBidGQ4rROhMCrsup0qUA)

export const CODE = {
  SUCCESS: 10000,
  SYSTEM_ERROR: 10001,
  PARAMETER_ERROR: 10002,
  OTP_EXPIRED: 11002,
  TOO_MANY_OTP_ATTEMPTS: 11004,
  OTP_NOT_VERIFIED_OR_ALREADY_USED: 11008,
  INVALID_JWT_TOKEN: 20062,
  INSUFFICIENT_BALANCE: 40009,
  ORDER_NUMBER_ERROR: 40051,
  ORDER_NUMBER_OR_THIRD_PARTY_ORDER_NUMBER_ERROR: 40053,
  GROUP_ALREADY_EXISTS: 40082,
  UNAUTHORIZED: 40100,
  FORBIDDEN: 40300,
  DEVICE_BLACKLISTED: 40310,
  DEVICE_NOT_TRUSTED: 40320,
  DEVICE_WITHDRAW_LOCKED_TEMP: 40323,
  NOT_FOUND: 40400,
  TOO_MANY_REQUESTS: 42900,
  USER_NOT_FOUND: 92000,
} as const;

export const MESSAGE: Record<keyof typeof CODE, string> = {
  SUCCESS: 'Success',
  SYSTEM_ERROR: 'System Error',
  PARAMETER_ERROR: 'Parameter Error',
  OTP_EXPIRED: 'OTP Expired',
  TOO_MANY_OTP_ATTEMPTS: 'Too Many OTP Attempts',
  OTP_NOT_VERIFIED_OR_ALREADY_USED: 'OTP Invalid or Used',
  INVALID_JWT_TOKEN: 'Invalid JWT Token',
  INSUFFICIENT_BALANCE: 'Insufficient Balance',
  ORDER_NUMBER_ERROR: 'Order Number Error',
  ORDER_NUMBER_OR_THIRD_PARTY_ORDER_NUMBER_ERROR: 'Order Number Error',
  GROUP_ALREADY_EXISTS: 'Group Already Exists',
  UNAUTHORIZED: 'Unauthorized',
  FORBIDDEN: 'Forbidden',
  DEVICE_BLACKLISTED: 'Device banned due to security risks',
  DEVICE_NOT_TRUSTED: 'New device detected, verification required',
  DEVICE_WITHDRAW_LOCKED_TEMP: 'Withdrawals disabled for 24h on new devices',
  NOT_FOUND: 'Not Found',
  TOO_MANY_REQUESTS: 'Too Many Requests',
  USER_NOT_FOUND: 'User Not Found',
};

export const ERROR_KEYS = {
  SUCCESS: 'SUCCESS',
  SYSTEM_ERROR: 'SYSTEM_ERROR',
  PARAMETER_ERROR: 'PARAMETER_ERROR',
  OTP_EXPIRED: 'OTP_EXPIRED',
  TOO_MANY_OTP_ATTEMPTS: 'TOO_MANY_OTP_ATTEMPTS',
  OTP_NOT_VERIFIED_OR_ALREADY_USED: 'OTP_NOT_VERIFIED_OR_ALREADY_USED',
  INVALID_JWT_TOKEN: 'INVALID_JWT_TOKEN',
  INSUFFICIENT_BALANCE: 'INSUFFICIENT_BALANCE',
  ORDER_NUMBER_ERROR: 'ORDER_NUMBER_ERROR',
  ORDER_NUMBER_OR_THIRD_PARTY_ORDER_NUMBER_ERROR:
    'ORDER_NUMBER_OR_THIRD_PARTY_ORDER_NUMBER_ERROR',
  GROUP_ALREADY_EXISTS: 'GROUP_ALREADY_EXISTS',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  DEVICE_BLACKLISTED: 'DEVICE_BLACKLISTED',
  DEVICE_NOT_TRUSTED: 'DEVICE_NOT_TRUSTED',
  DEVICE_WITHDRAW_LOCKED_TEMP: 'DEVICE_WITHDRAW_LOCKED_TEMP',
  NOT_FOUND: 'NOT_FOUND',
  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
} as const;

export type CodeKey = keyof typeof CODE;
export type CodeValue = (typeof CODE)[CodeKey];
export const codeOf = (k: CodeKey): CodeValue => CODE[k];
export const messageOf = (k: CodeKey): string => MESSAGE[k];
export const isCodeKey = (v: string): v is CodeKey => v in CODE;
