export const TRANSLATIONS = {
  en: {
    dashboard: 'Dashboard',
    users: 'User Management',
    admin: 'Admin Accounts',
    products: 'Products',
    categories: 'Categories',
    actSection: 'Act Sections',
    banners: 'Banners',
    groups: 'Group Buying',
    orders: 'Orders & Delivery',
    kyc: 'KYC Review',
    address: 'Address',
    marketing: 'Marketing',
    finance: 'Finance Center',
    finance_page: 'Finance',
    paymentChannels: 'Payment Channels',
    logout: 'Logout',
    revenue: 'Total Revenue',
    activeUsers: 'Active Users',
    newOrders: 'New Orders',
    add: 'Add New',
    edit: 'Edit',
    delete: 'Delete',
    save: 'Save',
    cancel: 'Cancel',
    search: 'Search...',
    status: 'Status',
    actions: 'Actions',
    kyc_pending: 'KYC Pending',
    notifications: 'Notifications',
    analytics: 'Data Analytics',
    operationLogs: 'Operation Logs',
    roles: 'Role Management',
    im: 'Customer Service',
    supportChannels: 'Support Channels',
    ads: 'Advertisements',
    flashSale: 'Flash Sale',
    loginLogs: 'Login Logs',
    luckyDraw: 'Lucky Draw',
    settings: 'System Config',
    pendingApplications: 'Pending Applications',
  },
  zh: {
    dashboard: '仪表盘',
    users: '用户管理',
    admin: '管理员账号',
    products: '商品管理',
    categories: '分类管理',
    actSection: '活动区块',
    banners: '轮播图',
    groups: '拼团管理',
    orders: '订单与发货',
    kyc: 'KYC 审核',
    address: '收货地址',
    marketing: '营销中心',
    finance: '财务中心',
    finance_page: '财务明细',
    paymentChannels: '支付渠道',
    logout: '退出登录',
    revenue: '总收入',
    activeUsers: '活跃用户',
    newOrders: '新订单',
    add: '添加',
    edit: '编辑',
    delete: '删除',
    save: '保存',
    cancel: '取消',
    search: '搜索...',
    status: '状态',
    actions: '操作',
    kyc_pending: 'KYC待审核',
    notifications: '消息推送',
    analytics: '数据分析',
    operationLogs: '操作日志',
    roles: '角色权限',
    im: '客服接待台',
    supportChannels: '客服渠道管理',
    ads: '广告管理',
    flashSale: '秒杀活动',
    loginLogs: '登录日志',
    luckyDraw: '福利抽奖',
    settings: '系统配置',
    pendingApplications: '待审批申请',
  },
};

export const ROLE_DISPLAY_NAMES: Record<string, string> = {
  SUPER_ADMIN: 'Super Admin',
  ADMIN: 'Admin',
  EDITOR: 'Editor',
  VIEWER: 'Viewer',
  FINANCE: 'Finance',
};
