export const TRANSLATIONS = {
  en: {
    dashboard: 'Dashboard',
    users: 'User Management',
    admin: 'Admin Accounts',
    products: 'Products',
    categories: 'Categories',
    actSection: 'Act Sections',
    banners: 'Banners',
    groups: 'Group Buying',
    orders: 'Orders & Delivery',
    kyc: 'KYC Review',
    address: 'Address',
    marketing: 'Marketing',
    finance: 'Finance Center',
    finance_page: 'Finance',
    paymentChannels: 'Payment Channels',
    system: 'System Settings',
    logout: 'Logout',
    revenue: 'Total Revenue',
    activeUsers: 'Active Users',
    newOrders: 'New Orders',
    add: 'Add New',
    edit: 'Edit',
    delete: 'Delete',
    save: 'Save',
    cancel: 'Cancel',
    search: 'Search...',
    status: 'Status',
    actions: 'Actions',
    kyc_pending: 'KYC Pending',
    winning: 'Winning',
    operations: 'Operations',
    lottery: 'Lottery Control',
    vip: 'VIP Config',
    notifications: 'Notifications',
    activity: 'Activity Config',
    admin_security: 'Security',
    content_cms: 'Content CMS',
    analytics: 'Data Analytics',
    operationLogs: 'Operation Logs',
    service: 'Service Center',
    roles: 'Role Management',
    im: 'Customer Service',
    ads: 'Advertisements',
    flashSale: 'Flash Sale',
    loginLogs: 'Login Logs',
    settings: 'System Config',
  },
  zh: {
    dashboard: '仪表盘',
    users: '用户管理',
    admin: '管理员账号',
    products: '商品管理',
    categories: '分类管理',
    actSection: '活动区块',
    banners: '轮播图',
    groups: '拼团管理',
    orders: '订单与发货',
    kyc: 'KYC 审核',
    address: '收货地址',
    marketing: '营销中心',
    finance: '财务中心',
    finance_page: '财务明细',
    paymentChannels: '支付渠道',
    system: '系统设置',
    logout: '退出登录',
    revenue: '总收入',
    activeUsers: '活跃用户',
    newOrders: '新订单',
    add: '添加',
    edit: '编辑',
    delete: '删除',
    save: '保存',
    cancel: '取消',
    search: '搜索...',
    status: '状态',
    actions: '操作',
    kyc_pending: 'KYC待审核',
    winning: '中奖',
    operations: '运营中心',
    lottery: '开奖控制',
    vip: 'VIP配置',
    notifications: '消息推送',
    activity: '活动配置',
    admin_security: '权限与安全',
    content_cms: '内容管理',
    analytics: '数据分析',
    operationLogs: '操作日志',
    service: '客服中心',
    roles: '角色权限',
    im: '客服接待台',
    ads: '广告管理',
    flashSale: '秒杀活动',
    loginLogs: '登录日志',
    settings: '系统配置',
  },
};
