const XLSX = require("xlsx");
const fs = require("fs");
const path = require("path");

// ================= 🗺️ 多项目配置 Map (核心) 🗺️ =================
// 你可以在这里无限添加项目，区分不同的 Sheet ID 和输出路径
const PROJECT_CONFIG = {
  // 项目 A: 商城 (默认)
  shop: {
    sheetId: "1E1otNTsU-GVKPvEf7qaC3dsBidGQ4rROhMCrsup0qUA", // 商城的表格 ID
    api: "../../apps/api/src/common/error-codes.gen.ts", // 后端输出路径
    client:
      "/Volumes/MySSD/work/dev/flutter_happy_app/lib/core/constants/app_errors.dart", // 前端输出路径
  },

  // 项目 B: 管理后台 (示例)
  admin: {
    sheetId: "ANOTHER_SHEET_ID_HERE", // 假如有一个不同的表格
    api: "../../apps/admin-api/src/common/error-codes.gen.ts",
    client:
      "/Volumes/MySSD/work/dev/flutter_happy_app/lib/core/constants/app_errors.dart",
  },

  // 也可以同一个 Sheet，但是只输出到不同位置
  // 'driver': { ... }
};

// ===============================================================

async function generate() {
  // 🎯 获取命令行参数
  // 参数 1: 项目名称 (默认为 'shop')
  const projectKey = process.argv[2] || "shop";
  // 参数 2: 输出目标 (api / client / all)
  const target = process.argv[3];

  // 1. 读取配置
  const config = PROJECT_CONFIG[projectKey];
  if (!config) {
    console.error(`❌ 错误: 找不到项目配置 "${projectKey}"`);
    console.error(`👉 可用项目: ${Object.keys(PROJECT_CONFIG).join(", ")}`);
    process.exit(1);
  }

  console.log(`🚀 正在构建项目: [${projectKey.toUpperCase()}]`);

  // 2. 生成下载链接
  // 如果你需要指定 Sheet 的某个 Tab，可以在这里拼接 &gid=xxx
  const url = `https://docs.google.com/spreadsheets/d/${config.sheetId}/export?format=xlsx`;
  console.log(`☁️  同步数据源...`);

  try {
    const response = await fetch(url);
    if (!response.ok) throw new Error(`下载失败 (HTTP ${response.status})`);

    const arrayBuffer = await response.arrayBuffer();
    const workbook = XLSX.read(arrayBuffer, { type: "buffer" });
    const sheet = workbook.Sheets[workbook.SheetNames[0]];
    const rawData = XLSX.utils.sheet_to_json(sheet);

    // 3. 数据清洗
    const codes = rawData
      .filter((row) => row.Code && row.Key)
      .sort((a, b) => a.Code - b.Code)
      .map((row) => ({
        Code: row.Code,
        Key: row.Key.trim().toUpperCase(),
        Message: row.Message || "",
        Category: row.Category || "99_其他",
      }));

    console.log(`✅ 解析成功: ${codes.length} 条数据`);

    // =========================================================
    // 4. 生成逻辑
    // =========================================================

    // --- 生成后端 (API) ---
    // 条件：没传 target 或者 target 是 'api'，且配置里有 api 路径
    if ((!target || target === "api") && config.api) {
      const outPath = path.resolve(__dirname, config.api);
      const content = generateTsContent(codes, config.sheetId);
      ensureDir(outPath);
      fs.writeFileSync(outPath, content);
      console.log(`📦 [API] 已生成: ${config.api}`);
    }

    // --- 生成前端 (Client) ---
    // 条件：没传 target 或者 target 是 'client'，且配置里有 client 路径
    if ((!target || target === "client") && config.client) {
      const outPath = path.resolve(__dirname, config.client);

      // 判断前端是 Dart (Flutter) 还是 TS (React/Vue)
      // 简单的判断：如果路径以 .dart 结尾生成 Dart，否则生成 TS
      if (outPath.endsWith(".dart")) {
        const content = generateDartContent(codes);
        ensureDir(outPath);
        fs.writeFileSync(outPath, content);
        console.log(`📱 [Flutter] 已生成: ${config.client}`);
      } else {
        // 如果前端也是 TS (比如后台管理系统)
        const content = generateTsContent(codes, config.sheetId);
        ensureDir(outPath);
        fs.writeFileSync(outPath, content);
        console.log(`💻 [Web] 已生成: ${config.client}`);
      }
    }
  } catch (error) {
    console.error("❌ 执行失败:", error.message);
  }
}

// ================= 🛠️ 辅助生成函数 🛠️ =================

function generateTsContent(codes, sourceId) {
  return `// *** AUTO-GENERATED. DO NOT EDIT. ***
// Source: Google Sheets (${sourceId})

export const CODE = {
${codes.map((c) => `  ${c.Key}: ${c.Code},`).join("\n")}
} as const;

export const MESSAGE: Record<keyof typeof CODE, string> = {
${codes.map((c) => `  ${c.Key}: '${c.Message}',`).join("\n")}
};

export const ERROR_KEYS = {
${codes.map((c) => `  ${c.Key}: '${c.Key}',`).join("\n")}
} as const;

export type CodeKey = keyof typeof CODE;
export type CodeValue = (typeof CODE)[CodeKey];
export const codeOf = (k: CodeKey): CodeValue => CODE[k];
export const messageOf = (k: CodeKey): string => MESSAGE[k];
export const isCodeKey = (v: string): v is CodeKey => v in CODE;
`;
}

function generateDartContent(codes) {
  const grouped = {};
  codes.forEach((c) => {
    if (!grouped[c.Category]) grouped[c.Category] = [];
    grouped[c.Category].push(c);
  });
  const categories = Object.keys(grouped).sort();
  const toCamel = (s) =>
    s.toLowerCase().replace(/_([a-z])/g, (g) => g[1].toUpperCase());

  let content = `/// 🚀 AUTO-GENERATED BY packages/config/gen-codes.js
/// ❌ DO NOT EDIT MANUALLY

class AppErrors {
  AppErrors._();

`;
  categories.forEach((cat) => {
    content += `  // =========================================================\n`;
    content += `  // ${cat.replace(/^\d+_/, "")}\n`;
    content += `  // =========================================================\n\n`;
    grouped[cat].forEach((c) => {
      content += `  /// [${c.Code}] ${c.Message}\n`;
      content += `  static const int ${toCamel(c.Key)} = ${c.Code};\n\n`;
    });
  });
  content += `}\n`;
  return content;
}

function ensureDir(filePath) {
  const dirname = path.dirname(filePath);
  if (!fs.existsSync(dirname)) fs.mkdirSync(dirname, { recursive: true });
}

generate();
