# ========================
# 1. 内存管理 (新增核心)
# ========================
# 限制最大使用 512MB 内存
maxmemory 512mb

# 策略：内存满了，优先删除那些“设置了过期时间”且“很久没用”的老数据
# 这样可以保护那些没有过期时间的永久数据不被误删
maxmemory-policy volatile-lru

# ========================
# 2. 持久化 (防断电)
# ========================
appendonly yes
appendfilename "appendonly.aof"
appendfsync everysec

save 900 1
save 300 10
save 60 10000

# ========================
# 3. Docker 基础配置
# ========================
dir /data
bind 0.0.0.0
protected-mode no