# Use the base image from the monorepo Dockerfile
# # This Dockerfile is for the development environment of the API workspace.
# # It uses the base image defined in Dockerfile.base as its starting point.
# before_script: docker build -f Dockerfile.base -t lucky-monorepo-base .
# you should run this command to build the base image before building this Dockerfile.

FROM lucky-monorepo-base

WORKDIR /app

COPY . .

WORKDIR /app/apps/api

CMD ["yarn", "workspace", "@lucky/api", "start:dev"]

